parcelRequire=function(e,r,n,t){function i(n,t){function o(e){return i(o.resolve(e))}function c(r){return e[n][1][r]||r}if(!r[n]){if(!e[n]){var l="function"==typeof parcelRequire&&parcelRequire;if(!t&&l)return l(n,!0);if(u)return u(n,!0);if(f&&"string"==typeof n)return f(n);var p=new Error("Cannot find module '"+n+"'");throw p.code="MODULE_NOT_FOUND",p}o.resolve=c;var a=r[n]=new i.Module(n);e[n][0].call(a.exports,o,a,a.exports,this)}return r[n].exports}function o(e){this.id=e,this.bundle=i,this.exports={}}var u="function"==typeof parcelRequire&&parcelRequire,f="function"==typeof require&&require;i.isParcelRequire=!0,i.Module=o,i.modules=e,i.cache=r,i.parent=u;for(var c=0;c<n.length;c++)i(n[c]);if(n.length){var l=i(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):t&&(this[t]=l)}return i}({2:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var t=require("react-dom/server");const e=e=>`\n  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n  ${(0,t.renderToStaticMarkup)(e)}\n`;exports.default=e;
},{}],12:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])}return e},r=require("react"),t=n(r);function n(e){return e&&e.__esModule?e:{default:e}}function l(e,r){var t={};for(var n in e)r.indexOf(n)>=0||Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);return t}const a=r=>{let n=r.style,a=l(r,["style"]);return t.default.createElement("table",e({},a,{border:"0",cellPadding:"0",cellSpacing:"0",style:e({margin:0,padding:0,border:"none",borderSpacing:0,borderCollapse:"collapse",verticalAlign:"top",width:"100%"},n)}))};exports.default=a;
},{}],13:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])}return e},r=require("react"),t=n(r);function n(e){return e&&e.__esModule?e:{default:e}}function o(e,r){var t={};for(var n in e)r.indexOf(n)>=0||Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);return t}const a=r=>{let n=r.style,a=o(r,["style"]);return t.default.createElement("tr",e({},a,{style:e({margin:0,padding:0,border:"none",borderSpacing:0,borderCollapse:"collapse",verticalAlign:"top",width:"100%"},n)}))};exports.default=a;
},{}],14:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])}return e},r=require("react"),t=n(r);function n(e){return e&&e.__esModule?e:{default:e}}function o(e,r){var t={};for(var n in e)r.indexOf(n)>=0||Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);return t}const a=r=>{let n=r.style,a=o(r,["style"]);return t.default.createElement("td",e({},a,{style:e({margin:0,padding:0,border:"none",borderSpacing:0,borderCollapse:"collapse",verticalAlign:"top",width:"100%"},n)}))};exports.default=a;
},{}],11:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("react"),t=c(e),r=require("prop-types"),a=c(r),l=require("./Table"),i=c(l),n=require("./Tr"),d=c(n),u=require("./Td"),o=c(u);function c(e){return e&&e.__esModule?e:{default:e}}const f=({children:e})=>t.default.createElement(i.default,{"data-component":"body",style:{width:"100%",height:"100%",backgroundColor:"white"}},t.default.createElement(d.default,null,t.default.createElement(o.default,{align:"center",valign:"top",style:{wordWrap:"break-word",fontSize:16,lineHeight:"1.3",color:"#0a0a0a",fontFamily:'"Circular",Helvetica,Arial,sans-serif',fontWeight:"normal"}},t.default.createElement("center",{style:{width:"100%",minWidth:580}},e))));f.propTypes={children:a.default.any.isRequired},exports.default=f;
},{"./Table":12,"./Tr":13,"./Td":14}],3:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("react"),t=d(e),l=require("prop-types"),n=d(l),r=require("./Body"),a=d(r);function d(e){return e&&e.__esModule?e:{default:e}}const i=({title:l,preview:n,children:r})=>t.default.createElement("html",{xmlns:"http://www.w3.org/1999/xhtml"},t.default.createElement("head",null,t.default.createElement("meta",{name:"viewport",content:"width=device-width, initial-scale=1.0"}),t.default.createElement("meta",{httpEquiv:"Content-Type",content:"text/html; charset=UTF-8"}),t.default.createElement("title",null,l),t.default.createElement("style",null,"\n        * {\n          margin: 0;\n          padding: 0;\n          border: none;\n          box-sizing: border-box;\n        }\n      ")),t.default.createElement("body",{style:{margin:0,padding:0,boxSizing:"border-box",backgroundColor:"white"}},n&&t.default.createElement(e.Fragment,null,t.default.createElement("div",{style:{display:"none",maxHeight:0,overflow:"hidden"}},n),t.default.createElement("div",{style:{display:"none",maxHeight:0,overflow:"hidden"}}," ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌   ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ")),t.default.createElement(a.default,null,r)));i.propTypes={title:n.default.string.isRequired,preview:n.default.string,children:n.default.any.isRequired},exports.default=i;
},{"./Body":11}],4:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var r=arguments[t];for(var a in r)Object.prototype.hasOwnProperty.call(r,a)&&(e[a]=r[a])}return e},t=require("react"),r=s(t),a=require("prop-types"),l=s(a),u=require("./Table"),n=s(u),d=require("./Tr"),i=s(d),o=require("./Td"),c=s(o);function s(e){return e&&e.__esModule?e:{default:e}}const f=({style:t,children:a})=>r.default.createElement(n.default,{"data-component":"container",style:e({width:580,maxWidth:580,margin:"0 auto"},t)},r.default.createElement(i.default,null,r.default.createElement(c.default,null,a)));f.propTypes={children:l.default.any.isRequired},exports.default=f;
},{"./Table":12,"./Tr":13,"./Td":14}],5:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var a in t)Object.prototype.hasOwnProperty.call(t,a)&&(e[a]=t[a])}return e},r=require("react"),t=c(r),a=require("prop-types"),l=c(a),n=require("./Table"),u=c(n),o=require("./Tr"),s=c(o);function c(e){return e&&e.__esModule?e:{default:e}}const d=({style:r,children:a})=>t.default.createElement(u.default,{"data-component":"row",style:e({display:"table"},r)},t.default.createElement(s.default,null,a));d.propTypes={children:l.default.any},exports.default=d;
},{"./Table":12,"./Tr":13}],6:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var r=arguments[t];for(var n in r)Object.prototype.hasOwnProperty.call(r,n)&&(e[n]=r[n])}return e},t=require("react"),r=d(t),n=require("prop-types"),a=d(n),o=require("./Td"),i=d(o);function d(e){return e&&e.__esModule?e:{default:e}}function u(e,t){var r={};for(var n in e)t.indexOf(n)>=0||Object.prototype.hasOwnProperty.call(e,n)&&(r[n]=e[n]);return r}const l={1:`${100/12}%`,2:`${200/12}%`,3:"25%",4:`${400/12}%`,5:`${500/12}%`,6:"50%",7:`${700/12}%`,8:`${800/12}%`,9:"75%",10:`${1e3/12}%`,11:`${1100/12}%`,12:"100%"},p=t=>{let n=t.width,a=t.style,o=u(t,["width","style"]);return r.default.createElement(i.default,e({"data-component":"column",style:e({width:l[n.toString()],marginTop:0,marginBottom:0,marginLeft:"auto",marginRight:"auto",paddingTop:0,paddingBottom:0,paddingLeft:15,paddingRight:15},a)},o))};p.defaultProps={width:12},p.propTypes={width:a.default.oneOfType([a.default.string,a.default.number]).isRequired,children:a.default.any},exports.default=p;
},{"./Td":14}],7:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var a in t)Object.prototype.hasOwnProperty.call(t,a)&&(e[a]=t[a])}return e},r=require("react"),t=p(r),a=require("prop-types"),n=p(a),l=require("./Table"),u=p(l),d=require("./Tr"),o=p(d),i=require("./Td"),c=p(i);function p(e){return e&&e.__esModule?e:{default:e}}function f(e,r){var t={};for(var a in e)r.indexOf(a)>=0||Object.prototype.hasOwnProperty.call(e,a)&&(t[a]=e[a]);return t}const s=r=>{var a=r.style;let n=a.padding,l=f(a,["padding"]),d=r.children,i=f(r,["style","children"]);return t.default.createElement(u.default,e({"data-component":"box",style:e({},l)},i),t.default.createElement(o.default,null,t.default.createElement(c.default,{style:{padding:n}},d)))};s.propTypes={children:n.default.any},exports.default=s;
},{"./Table":12,"./Tr":13,"./Td":14}],8:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])}return e},r=require("react"),t=o(r),n=require("prop-types"),a=o(n);function o(e){return e&&e.__esModule?e:{default:e}}function l(e,r){var t={};for(var n in e)r.indexOf(n)>=0||Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);return t}const u=r=>{let n=r.style,a=l(r,["style"]);return t.default.createElement("p",e({},a,{style:e({margin:0,padding:0},n)}))};u.PropTypes={children:a.default.any.isRequired},exports.default=u;
},{}],9:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])}return e},r=require("react"),t=o(r),n=require("prop-types"),a=o(n);function o(e){return e&&e.__esModule?e:{default:e}}function s(e,r){var t={};for(var n in e)r.indexOf(n)>=0||Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);return t}const i=r=>{let n=r.style,a=s(r,["style"]);return t.default.createElement("img",e({},a,{style:e({margin:0,padding:0,border:"none"},n)}))};i.propTypes={src:a.default.string.isRequired,alt:a.default.string.isRequired},exports.default=i;
},{}],10:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=Object.assign||function(e){for(var r=1;r<arguments.length;r++){var t=arguments[r];for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])}return e},r=require("react"),t=l(r),n=require("prop-types"),a=l(n);function l(e){return e&&e.__esModule?e:{default:e}}function i(e,r){var t={};for(var n in e)r.indexOf(n)>=0||Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);return t}const o=r=>{let n=r.style,a=i(r,["style"]);return t.default.createElement("a",e({},a,{target:"_blank",style:e({margin:0,padding:0,display:"inline-block"},n)}))};o.propTypes={href:a.default.string.isRequired,children:a.default.any.isRequired},exports.default=o;
},{}],1:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Link=exports.Image=exports.Text=exports.Box=exports.Column=exports.Row=exports.Container=exports.Email=exports.renderToHtml=void 0;var e=require("./renderToHtml"),o=T(e),r=require("./components/Email"),t=T(r),n=require("./components/Container"),s=T(n),p=require("./components/Row"),u=T(p),x=require("./components/Column"),i=T(x),l=require("./components/Box"),a=T(l),m=require("./components/Text"),d=T(m),f=require("./components/Image"),c=T(f),q=require("./components/Link"),C=T(q);function T(e){return e&&e.__esModule?e:{default:e}}exports.renderToHtml=o.default,exports.Email=t.default,exports.Container=s.default,exports.Row=u.default,exports.Column=i.default,exports.Box=a.default,exports.Text=d.default,exports.Image=c.default,exports.Link=C.default;
},{"./renderToHtml":2,"./components/Email":3,"./components/Container":4,"./components/Row":5,"./components/Column":6,"./components/Box":7,"./components/Text":8,"./components/Image":9,"./components/Link":10}]},{},[1], null)
//# sourceMappingURL=/index.map